---

- name: Add universe repo
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe
  when: setup_universe_repo

# to just apt upgrade, --tags=apt_upgrade[,reboot]
- name: Upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist
  tags: setup_apt_upgrade

- name: Setup standard packages
  apt:
    update_cache: yes
    name: '{{ item }}'
    state: present
  with_items:
    - locales
    - build-essential
    - ntp
    - htop
    - git
    - mercurial
  tags: setup_apt_packages

- name: Set timezone
  timezone:
    name: '{{ setup_timezone }}'
  tags: setup_timezone

- name: Set locale
  command: '/usr/sbin/update-locale LANG={{ setup_locale }} LC_ALL={{ setup_locale }}'

# set hostname to be of form: web1.rc.slated
- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}.{{ target }}.{{ application }}'
  tags: setup_hostname

- name: Update /etc/hostname file
  lineinfile:
    dest: /etc/hostname
    regexp: .*
    line: '{{ inventory_hostname }}.{{ target }}.{{ application }}'
    create: yes
  tags: setup_hostname

- name: Update /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '^.* {{ inventory_hostname }}$'
    line: '{{ ansible_default_ipv4.address }} {{ inventory_hostname }}.{{ target }}.{{ application }}'
    create: yes
  tags: setup_hostname
